### PR TITLE
Multiple Changes

### PR DESCRIPTION
**Pull request by sameerjvn-old**
- Added list of images for following new versions - 
> 3.3.0.12
> 3.3.0.13
> 3.3.0.14
> 3.3.0.15
> 3.5
- Added flag `-u` or `--uninstall` for `install.sh` for uninstalling harbor.
- Added `restart: unless-stopped` for all harbor containers so harbor comes back up if any container or VM crashes.

### CODE REVIEW

**Comment by sameerjvn-old** [comment]
@deepio-oc could you review this?

**Comment by deepio-oc** [comment]
why do we have so many versions in the latest tree. I believe we discussed this in the past and agreed to tag the repo and keep latest version in the main. Right ?

**Comment by sameerjvn-old** [comment]
@deepio-oc Yes, but the flag --dkube-version for ./upload.sh would be unnecessary since the branch only contains the list for one version. Is this fine?

**Comment by deepio-oc** [comment]
we can leave the flag for now.

**Review by deepio-oc — APPROVED** [review]

**Pull request merged**
